# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f788db2016688658cb607d1b63937a58126caecbdda1cb48790083e58614463e6f565844948df3d4be04125f4de21b831db1e5a8e2915d2fc59f6ef93d1eaf5

test:
  secret_key_base: bf301bd13c0ff15f832e0c99c3e3315508db7563cee54480250ebfb4361a1064dcc78ea42872deaefbb1dfb5cff6f271371e52c253a5f381aa21100ad761bb4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
